### PR TITLE
Wip master

### PR DESCRIPTION
**Pull request by alexanderGugel**
Hello Thomas!

This became a bit longer than expected, but I wanted to use an app that naturally uses lots of different actions.

There are quite a bit of tests that cover (pretty much) everything. I tried to write them in a way that allows the students to follow them one-by-one. Therefore there is quite some redundancy in there (in terms of testing), but I think it's more important to keep them readable in this case.

I know this is quite a long lesson, so I think we might want to prepare some of the components and focus on the actions instead.... Anyways, curious about your thoughts on this one.

Thanks!

### CODE REVIEW

**Comment by thomastuts** [comment]
This is amazing, so many tests! 😍  I don't really have anything to say about the exercise content — awesome job on that! Some nitpick-y feedback:
- Should we move actions into an `actions/` folder? We shouldn't aim for production-level architecture here, but the goal is to guide the students towards _some_ kind of modular, scalable architecture
- I think we should avoid passing events to the actions (but just the pure value where applicable, like the cell's value on cell change), and instead run `event.preventDefault()` in the handlers in the component. This makes for some more boilerplate code in the components, but it's more in line with how Redux actions are written. What do you think?
- @AnnJohn how does the learn.co platform handle referencing files (`All our [actions](./components/actions.js)...`)? Will this show the file in the browser or is this going to break things?
- I think we can use some more ES2015 features to showcase in the solution code — I've added a separate branch with some suggestions (along with removing the event stuff in actions), see https://github.com/learn-co-curriculum/react-actions-lab/commit/189a130a6b48dbd697476fa54c3b97de3f398952 for the changes. You don't have to use this, just wanted to throw it out there since we want students to try to use as much new ES2015 features as possible to become familiar with them. (The tests on that branch haven't been changed yet and will fail, by the way)

**Comment by AnnJohn** [comment]
@thomastuts for referencing files, you would need to have the full url of the file (and not just, for example, (./components/actions.js) ) since that won't render correctly on Learn. 

thanks!

**Comment by alexanderGugel** [comment]
> Should we move actions into an `actions/` folder? We shouldn't aim for production-level architecture here, but the goal is to guide the students towards _some_ kind of modular, scalable architecture

Done. Was also thinking of moving them into separate files, but that seemed a bit excessive.

> I think we should avoid passing events to the actions (but just the pure value where applicable, like the cell's value on cell change), and instead run `event.preventDefault()` in the handlers in the component. This makes for some more boilerplate code in the components, but it's more in line with how Redux actions are written. What do you think?

Hmmm... not sure, since those are already pretty coupled to the component itself anyways (they call `.setState` on this). Should we make them actual "really" pure action creators?

> I think we can use some more ES2015 features to showcase in the solution code — I've added a separate branch with some suggestions (along with removing the event stuff in actions), see https://github.com/learn-co-curriculum/react-actions-lab/commit/189a130a6b48dbd697476fa54c3b97de3f398952 for the changes. You don't have to use this, just wanted to throw it out there since we want students to try to use as much new ES2015 features as possible to become familiar with them. (The tests on that branch haven't been changed yet and will fail, by the way)

Done. Great idea.

**Comment by thomastuts** [comment]
> Done. Was also thinking of moving them into separate files, but that seemed a bit excessive.

Yeah, I think having them in one file is fine for now. 👍  We want to get students to start noticing and thinking about project architecture, but we should avoid too much busywork by having them rummage through separate files.

> Hmmm... not sure, since those are already pretty coupled to the component itself anyways (they call `.setState` on this). Should we make them actual "really" pure action creators?

We shouldn't focus on the action creators concept yet, but it's at least valuable to show students how they can decouple the actions from their components completely. I feel like having the event stuff in the actions themselves couples them too tightly to the way they're being used in the component. For example, what if you only want a cell to update by pressing a 'Save' button in the cell instead of using `onChange`, etc. This is probably too far-fetched and things will work just fine either way, just something to think about.

---

Re. the ES2015 solution branch I proposed: awesome comments there 🔥  Feel free to use whatever you'd like, they were merely suggestions.

If you'd rather keep things as-is, let me know and we'll get this merged in. That goes for any of my above comments, it's just stuff we can discuss, not something that _needs_ to change.

**Comment by alexanderGugel** [comment]
@thomastuts I think the linter doesn't like me 😢 — something wrong with the license "invalid or missing license content" (didn't touch it). Do you know anything about this?

**Comment by thomastuts** [comment]
@alexanderGugel I'm sure it hurts to see a failing linting check, but you can ignore the Learn linting for now — it seems it hasn't been updated in quite some time. Don't worry about the `CONTRIBUTING.md` and `LICENSE.md` files!

**Comment by alexanderGugel** [comment]
Actually had a merge conflict because I removed the `require` test from the `index.js` — My bad 😞 

Can I merge?

**Comment by AnnJohn** [comment]
@alexanderGugel don't worry about the linter like thomas said. Otherwise if all is good, then merge away. thanks!

**Pull request merged**
